import { Company } from "./types";

export const companies: Company[] = [
    {
        id: "1",
        name: "Tokopedia",
        slug: "tokopedia",
        industry: "Retail & E-Commerce",
        ownership: "Swasta",
        career_url: "https://www.tokopedia.com/careers",
        hash_signature: null,
        email: "careers@tokopedia.com",
        linkedin_url: "https://www.linkedin.com/company/tokopedia",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/tokopedia",
        status: "ACTIVE",
        last_verified_at: "2026-02-28T10:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-28T10:00:00Z",
    },
    {
        id: "2",
        name: "Gojek",
        slug: "gojek",
        industry: "Technology & Digital",
        ownership: "Swasta",
        career_url: "https://www.gojek.com/en-id/careers/",
        hash_signature: null,
        email: null,
        linkedin_url: "https://www.linkedin.com/company/gojek",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/gojekindonesia",
        status: "ACTIVE",
        last_verified_at: "2026-02-27T08:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-27T08:00:00Z",
    },
    {
        id: "3",
        name: "Bank Central Asia (BCA)",
        slug: "bank-bca",
        industry: "Financial Services",
        ownership: "Swasta",
        career_url: "https://karir.bca.co.id/",
        hash_signature: null,
        email: "halo@bca.co.id",
        linkedin_url: "https://www.linkedin.com/company/pt-bank-central-asia-tbk",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/goodlifebca",
        status: "ACTIVE",
        last_verified_at: "2026-02-28T12:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-28T12:00:00Z",
    },
    {
        id: "4",
        name: "Shopee Indonesia",
        slug: "shopee-indonesia",
        industry: "Retail & E-Commerce",
        ownership: "Swasta",
        career_url: "https://careers.shopee.co.id/",
        hash_signature: null,
        email: null,
        linkedin_url: "https://www.linkedin.com/company/shopee",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/shopee_id",
        status: "ACTIVE",
        last_verified_at: "2026-02-26T09:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-26T09:00:00Z",
    },
    {
        id: "5",
        name: "Telkom Indonesia",
        slug: "telkom-indonesia",
        industry: "Telecommunications",
        ownership: "BUMN/D",
        career_url: "https://rekrutmen.telkom.co.id/",
        hash_signature: null,
        email: "recruitment@telkom.co.id",
        linkedin_url: "https://www.linkedin.com/company/telkom-indonesia",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/telkom_id",
        status: "ACTIVE",
        last_verified_at: "2026-02-25T14:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-25T14:00:00Z",
    },
    {
        id: "6",
        name: "Unilever Indonesia",
        slug: "unilever-indonesia",
        industry: "Consumer Goods (FMCG)",
        ownership: "Swasta",
        career_url: "https://careers.unilever.com/location/indonesia/34583/1643084/",
        hash_signature: null,
        email: null,
        linkedin_url: "https://www.linkedin.com/company/unilever",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/unileverid",
        status: "ACTIVE",
        last_verified_at: "2026-02-27T16:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-27T16:00:00Z",
    },
    {
        id: "7",
        name: "Astra International",
        slug: "astra-international",
        industry: "Manufacturing & Industrial",
        ownership: "Swasta",
        career_url: "https://career.astra.co.id/",
        hash_signature: null,
        email: "recruitment@astra.co.id",
        linkedin_url: "https://www.linkedin.com/company/astra-international",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/astra_id",
        status: "ACTIVE",
        last_verified_at: "2026-02-26T11:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-26T11:00:00Z",
    },
    {
        id: "8",
        name: "Pertamina",
        slug: "pertamina",
        industry: "Energy & Natural Resources",
        ownership: "BUMN/D",
        career_url: "https://recruitment.pertamina.com/",
        hash_signature: null,
        email: null,
        linkedin_url: "https://www.linkedin.com/company/pertamina",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/pertamina",
        status: "ACTIVE",
        last_verified_at: "2026-02-28T08:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-28T08:00:00Z",
    },
    {
        id: "9",
        name: "Bukalapak",
        slug: "bukalapak",
        industry: "Retail & E-Commerce",
        ownership: "Swasta",
        career_url: "https://careers.bukalapak.com/",
        hash_signature: null,
        email: "career@bukalapak.com",
        linkedin_url: "https://www.linkedin.com/company/bukalapak-com",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/bukalapak",
        status: "ACTIVE",
        last_verified_at: "2026-02-25T10:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-25T10:00:00Z",
    },
    {
        id: "10",
        name: "Traveloka",
        slug: "traveloka",
        industry: "Technology & Digital",
        ownership: "Swasta",
        career_url: "https://www.traveloka.com/en-id/careers",
        hash_signature: null,
        email: null,
        linkedin_url: "https://www.linkedin.com/company/traveloka",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/traveloka",
        status: "ACTIVE",
        last_verified_at: "2026-02-27T14:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-27T14:00:00Z",
    },
    {
        id: "11",
        name: "Bank Mandiri",
        slug: "bank-mandiri",
        industry: "Financial Services",
        ownership: "BUMN/D",
        career_url: "https://www.bankmandiri.co.id/mandiri-career",
        hash_signature: null,
        email: null,
        linkedin_url: "https://www.linkedin.com/company/bank-mandiri",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/bankmandiri",
        status: "ACTIVE",
        last_verified_at: "2026-02-28T09:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-28T09:00:00Z",
    },
    {
        id: "12",
        name: "XL Axiata",
        slug: "xl-axiata",
        industry: "Telecommunications",
        ownership: "Swasta",
        career_url: "https://careers.xl.co.id/",
        hash_signature: null,
        email: "recruitment@xl.co.id",
        linkedin_url: "https://www.linkedin.com/company/xl-axiata",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/myXL",
        status: "ACTIVE",
        last_verified_at: "2026-02-24T11:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-24T11:00:00Z",
    },
    {
        id: "13",
        name: "Grab Indonesia",
        slug: "grab-indonesia",
        industry: "Technology & Digital",
        ownership: "Swasta",
        career_url: "https://grab.careers/",
        hash_signature: null,
        email: null,
        linkedin_url: "https://www.linkedin.com/company/grabapp",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/grab_id",
        status: "ACTIVE",
        last_verified_at: "2026-02-27T15:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-27T15:00:00Z",
    },
    {
        id: "14",
        name: "Indofood",
        slug: "indofood",
        industry: "Consumer Goods (FMCG)",
        ownership: "Swasta",
        career_url: "https://career.indofood.com/",
        hash_signature: null,
        email: "recruitment@indofood.co.id",
        linkedin_url: "https://www.linkedin.com/company/indofood",
        whatsapp: null,
        instagram_url: null,
        status: "ACTIVE",
        last_verified_at: "2026-02-26T14:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-26T14:00:00Z",
    },
    {
        id: "15",
        name: "Halodoc",
        slug: "halodoc",
        industry: "Healthcare & Pharmaceutical",
        ownership: "Swasta",
        career_url: "https://www.halodoc.com/careers",
        hash_signature: null,
        email: "careers@halodoc.com",
        linkedin_url: "https://www.linkedin.com/company/halodoc",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/halodoc",
        status: "ACTIVE",
        last_verified_at: "2026-02-28T07:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-28T07:00:00Z",
    },
    {
        id: "16",
        name: "J&T Express",
        slug: "jnt-express",
        industry: "Transportation & Logistics",
        ownership: "Swasta",
        career_url: "https://jet.co.id/career",
        hash_signature: null,
        email: "hr@jet.co.id",
        linkedin_url: "https://www.linkedin.com/company/j&t-express-indonesia",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/jabordjekssindonesia",
        status: "ACTIVE",
        last_verified_at: "2026-02-25T13:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-25T13:00:00Z",
    },
    {
        id: "17",
        name: "Kompas Gramedia",
        slug: "kompas-gramedia",
        industry: "Media & Entertainment",
        ownership: "Swasta",
        career_url: "https://career.kompasgramedia.com/",
        hash_signature: null,
        email: "recruitment@kompasgramedia.com",
        linkedin_url: "https://www.linkedin.com/company/kompas-gramedia",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/kompasgramedia",
        status: "ACTIVE",
        last_verified_at: "2026-02-24T16:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-24T16:00:00Z",
    },
    {
        id: "18",
        name: "Ruangguru",
        slug: "ruangguru",
        industry: "Education",
        ownership: "Swasta",
        career_url: "https://career.ruangguru.com/",
        hash_signature: null,
        email: "career@ruangguru.com",
        linkedin_url: "https://www.linkedin.com/company/ruangguru",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/ruangguru",
        status: "FLAGGED",
        last_verified_at: "2026-02-20T10:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-20T10:00:00Z",
    },
    {
        id: "19",
        name: "Sinar Mas Land",
        slug: "sinar-mas-land",
        industry: "Property & Construction",
        ownership: "Swasta",
        career_url: "https://career.sinarmasland.com/",
        hash_signature: null,
        email: "recruitment@sinarmasland.com",
        linkedin_url: "https://www.linkedin.com/company/sinarmasland",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/sinarmas_land",
        status: "ACTIVE",
        last_verified_at: "2026-02-27T09:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-27T09:00:00Z",
    },
    {
        id: "20",
        name: "Toyota Astra Motor",
        slug: "toyota-astra-motor",
        industry: "Manufacturing & Industrial",
        ownership: "Swasta",
        career_url: "https://www.toyota.astra.co.id/corporate-info/career",
        hash_signature: null,
        email: null,
        linkedin_url: "https://www.linkedin.com/company/toyota-astra-motor",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/toyotaid",
        status: "ACTIVE",
        last_verified_at: "2026-02-26T15:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-26T15:00:00Z",
    },
    {
        id: "21",
        name: "Bank Rakyat Indonesia (BRI)",
        slug: "bank-bri",
        industry: "Financial Services",
        ownership: "BUMN/D",
        career_url: "https://e-recruitment.bri.co.id/",
        hash_signature: null,
        email: null,
        linkedin_url: "https://www.linkedin.com/company/bank-bri",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/bankbri_id",
        status: "ACTIVE",
        last_verified_at: "2026-02-28T11:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-28T11:00:00Z",
    },
    {
        id: "22",
        name: "Blibli",
        slug: "blibli",
        industry: "Retail & E-Commerce",
        ownership: "Swasta",
        career_url: "https://careers.blibli.com/",
        hash_signature: null,
        email: "career@blibli.com",
        linkedin_url: "https://www.linkedin.com/company/bliblidotcom",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/bliblidotcom",
        status: "ACTIVE",
        last_verified_at: "2026-02-26T12:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-26T12:00:00Z",
    },
    {
        id: "23",
        name: "Tiket.com",
        slug: "tiketcom",
        industry: "Technology & Digital",
        ownership: "Swasta",
        career_url: "https://www.tiket.com/careers",
        hash_signature: null,
        email: "careers@tiket.com",
        linkedin_url: "https://www.linkedin.com/company/tiketcom",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/tiketcom",
        status: "FLAGGED",
        last_verified_at: "2026-02-18T10:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-18T10:00:00Z",
    },
    {
        id: "24",
        name: "Indosat Ooredoo Hutchison",
        slug: "indosat-ooredoo-hutchison",
        industry: "Telecommunications",
        ownership: "Swasta",
        career_url: "https://ioh.co.id/portal/id/career",
        hash_signature: null,
        email: null,
        linkedin_url: "https://www.linkedin.com/company/indosat-ooredoo-hutchison/",
        whatsapp: null,
        instagram_url: "https://www.instagram.com/indosatooredoohutchison",
        status: "ACTIVE",
        last_verified_at: "2026-02-27T13:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-27T13:00:00Z",
    },
    {
        id: "25",
        name: "Kalbe Farma",
        slug: "kalbe-farma",
        industry: "Healthcare & Pharmaceutical",
        ownership: "Swasta",
        career_url: "https://career.kalbe.co.id/",
        hash_signature: null,
        email: "recruitment@kalbe.co.id",
        linkedin_url: "https://www.linkedin.com/company/kalbe-farma",
        whatsapp: null,
        instagram_url: null,
        status: "ACTIVE",
        last_verified_at: "2026-02-25T15:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-25T15:00:00Z",
    },
];

// Helper functions for mock data operations
export function getCompanies(): Company[] {
    return companies;
}

export function getCompanyBySlug(slug: string): Company | undefined {
    return companies.find((c) => c.slug === slug);
}

export function searchCompanies(
    query: string,
    industry?: string,
    ownership?: string
): Company[] {
    let results = companies.filter((c) => c.status !== "PENDING");

    if (query) {
        const q = query.toLowerCase();
        results = results.filter((c) => c.name.toLowerCase().includes(q));
    }

    if (industry && industry !== "all") {
        results = results.filter((c) => c.industry === industry);
    }

    if (ownership && ownership !== "all") {
        results = results.filter((c) => c.ownership === ownership);
    }

    return results;
}

export function getStats() {
    const total = companies.filter((c) => c.status !== "PENDING").length;
    const active = companies.filter((c) => c.status === "ACTIVE").length;
    const flagged = companies.filter((c) => c.status === "FLAGGED").length;
    const pending = companies.filter((c) => c.status === "PENDING").length;
    const industries = [...new Set(companies.map((c) => c.industry))].length;
    return { total, active, flagged, pending, industries };
}
