import { Company } from "./types";

export const companies: Company[] = [
    {
        id: "1",
        name: "Tokopedia",
        slug: "tokopedia",
        industry: "E-Commerce",
        city: "Jakarta",
        description:
            "Platform e-commerce terbesar di Indonesia yang menghubungkan jutaan penjual dan pembeli. Bagian dari GoTo Group.",
        career_url: "https://www.tokopedia.com/careers",
        hash_signature: null,
        email: "careers@tokopedia.com",
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/tokopedia",
        whatsapp: null,
        maps_url: "https://maps.app.goo.gl/tokopedia",
        instagram_url: "https://www.instagram.com/tokopedia",
        status: "ACTIVE",
        last_verified_at: "2026-02-28T10:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-28T10:00:00Z",
    },
    {
        id: "2",
        name: "Gojek",
        slug: "gojek",
        industry: "Technology",
        city: "Jakarta",
        description:
            "Super app on-demand terkemuka di Asia Tenggara. Menyediakan layanan transportasi, pembayaran, pengiriman makanan, dan logistik.",
        career_url: "https://www.gojek.com/en-id/careers/",
        hash_signature: null,
        email: null,
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/gojek",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/gojekindonesia",
        status: "ACTIVE",
        last_verified_at: "2026-02-27T08:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-27T08:00:00Z",
    },
    {
        id: "3",
        name: "Bank Central Asia (BCA)",
        slug: "bank-bca",
        industry: "Banking & Finance",
        city: "Jakarta",
        description:
            "Salah satu bank swasta terbesar di Indonesia. Menyediakan layanan perbankan, kartu kredit, dan berbagai produk finansial.",
        career_url: "https://karir.bca.co.id/",
        hash_signature: null,
        email: "halo@bca.co.id",
        phone: "1500888",
        linkedin_url: "https://www.linkedin.com/company/pt-bank-central-asia-tbk",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/goodlifebca",
        status: "ACTIVE",
        last_verified_at: "2026-02-28T12:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-28T12:00:00Z",
    },
    {
        id: "4",
        name: "Shopee Indonesia",
        slug: "shopee-indonesia",
        industry: "E-Commerce",
        city: "Jakarta",
        description:
            "Platform e-commerce terkemuka di Asia Tenggara dan Taiwan. Menyediakan pengalaman belanja online yang mudah, aman, dan cepat.",
        career_url: "https://careers.shopee.co.id/",
        hash_signature: null,
        email: null,
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/shopee",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/shopee_id",
        status: "ACTIVE",
        last_verified_at: "2026-02-26T09:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-26T09:00:00Z",
    },
    {
        id: "5",
        name: "Telkom Indonesia",
        slug: "telkom-indonesia",
        industry: "Telekomunikasi",
        city: "Bandung",
        description:
            "BUMN telekomunikasi terbesar di Indonesia. Menyediakan layanan jaringan, internet (IndiHome), dan solusi digital.",
        career_url: "https://rekrutmen.telkom.co.id/",
        hash_signature: null,
        email: "recruitment@telkom.co.id",
        phone: "147",
        linkedin_url: "https://www.linkedin.com/company/telkom-indonesia",
        whatsapp: null,
        maps_url: "https://maps.app.goo.gl/telkom",
        instagram_url: "https://www.instagram.com/telabordjek_id",
        status: "ACTIVE",
        last_verified_at: "2026-02-25T14:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-25T14:00:00Z",
    },
    {
        id: "6",
        name: "Unilever Indonesia",
        slug: "unilever-indonesia",
        industry: "FMCG",
        city: "Tangerang",
        description:
            "Perusahaan multinasional FMCG terkemuka. Memproduksi produk rumah tangga, makanan, dan perawatan diri dengan merek ternama.",
        career_url: "https://careers.unilever.com/location/indonesia/34583/1643084/",
        hash_signature: null,
        email: null,
        phone: "0800-1558-000",
        linkedin_url: "https://www.linkedin.com/company/unilever",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/unileverid",
        status: "ACTIVE",
        last_verified_at: "2026-02-27T16:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-27T16:00:00Z",
    },
    {
        id: "7",
        name: "Astra International",
        slug: "astra-international",
        industry: "Otomotif",
        city: "Jakarta",
        description:
            "Konglomerasi bisnis terbesar di Indonesia, bergerak di bidang otomotif, jasa keuangan, alat berat, agribisnis, IT, dan properti.",
        career_url: "https://career.astra.co.id/",
        hash_signature: null,
        email: "recruitment@astra.co.id",
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/astra-international",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/aabordjek_id",
        status: "ACTIVE",
        last_verified_at: "2026-02-26T11:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-26T11:00:00Z",
    },
    {
        id: "8",
        name: "Pertamina",
        slug: "pertamina",
        industry: "Energi & Pertambangan",
        city: "Jakarta",
        description:
            "BUMN energi terbesar di Indonesia. Bergerak di bidang minyak & gas, energi baru terbarukan, dan petrokimia.",
        career_url: "https://recruitment.pertamina.com/",
        hash_signature: null,
        email: null,
        phone: "135",
        linkedin_url: "https://www.linkedin.com/company/pertamina",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/pertamina",
        status: "ACTIVE",
        last_verified_at: "2026-02-28T08:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-28T08:00:00Z",
    },
    {
        id: "9",
        name: "Bukalapak",
        slug: "bukalapak",
        industry: "E-Commerce",
        city: "Jakarta",
        description:
            "Platform e-commerce dan mitra pelapak online Indonesia. Fokus pada pengembangan UMKM dan digitalisasi warung.",
        career_url: "https://careers.bukalapak.com/",
        hash_signature: null,
        email: "career@bukalapak.com",
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/bukalapak-com",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/bukalapak",
        status: "ACTIVE",
        last_verified_at: "2026-02-25T10:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-25T10:00:00Z",
    },
    {
        id: "10",
        name: "Traveloka",
        slug: "traveloka",
        industry: "Technology",
        city: "Jakarta",
        description:
            "Platform lifestyle super app terkemuka di Asia Tenggara. Menyediakan layanan booking tiket, hotel, dan aktivitas.",
        career_url: "https://www.traveloka.com/en-id/careers",
        hash_signature: null,
        email: null,
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/traveloka",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/traveloka",
        status: "ACTIVE",
        last_verified_at: "2026-02-27T14:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-27T14:00:00Z",
    },
    {
        id: "11",
        name: "Bank Mandiri",
        slug: "bank-mandiri",
        industry: "Banking & Finance",
        city: "Jakarta",
        description:
            "Bank BUMN terbesar di Indonesia berdasarkan aset. Menyediakan layanan perbankan korporasi, komersial, mikro, dan ritel.",
        career_url: "https://www.bankmandiri.co.id/mandiri-career",
        hash_signature: null,
        email: null,
        phone: "14000",
        linkedin_url: "https://www.linkedin.com/company/bank-mandiri",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/bankmandiri",
        status: "ACTIVE",
        last_verified_at: "2026-02-28T09:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-28T09:00:00Z",
    },
    {
        id: "12",
        name: "XL Axiata",
        slug: "xl-axiata",
        industry: "Telekomunikasi",
        city: "Jakarta",
        description:
            "Operator telekomunikasi seluler terkemuka di Indonesia. Menyediakan layanan jaringan data, voice, dan solusi digital.",
        career_url: "https://careers.xl.co.id/",
        hash_signature: null,
        email: "recruitment@xl.co.id",
        phone: "817",
        linkedin_url: "https://www.linkedin.com/company/xl-axiata",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/myXL",
        status: "ACTIVE",
        last_verified_at: "2026-02-24T11:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-24T11:00:00Z",
    },
    {
        id: "13",
        name: "Grab Indonesia",
        slug: "grab-indonesia",
        industry: "Technology",
        city: "Jakarta",
        description:
            "Super app terkemuka di Asia Tenggara, menawarkan layanan transportasi, pengiriman, dan keuangan digital.",
        career_url: "https://grab.careers/",
        hash_signature: null,
        email: null,
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/grabapp",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/grab_id",
        status: "ACTIVE",
        last_verified_at: "2026-02-27T15:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-27T15:00:00Z",
    },
    {
        id: "14",
        name: "Indofood",
        slug: "indofood",
        industry: "FMCG",
        city: "Jakarta",
        description:
            "Perusahaan makanan terbesar di Indonesia, memproduksi mie instan, bumbu, makanan ringan, dan minuman.",
        career_url: "https://career.indofood.com/",
        hash_signature: null,
        email: "recruitment@indofood.co.id",
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/indofood",
        whatsapp: null,
        maps_url: null,
        instagram_url: null,
        status: "ACTIVE",
        last_verified_at: "2026-02-26T14:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-26T14:00:00Z",
    },
    {
        id: "15",
        name: "Halodoc",
        slug: "halodoc",
        industry: "Kesehatan",
        city: "Jakarta",
        description:
            "Platform teknologi kesehatan terkemuka di Indonesia, menyediakan konsultasi dokter online, pembelian obat, dan lab test.",
        career_url: "https://www.halodoc.com/careers",
        hash_signature: null,
        email: "careers@halodoc.com",
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/halodoc",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/halodoc",
        status: "ACTIVE",
        last_verified_at: "2026-02-28T07:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-28T07:00:00Z",
    },
    {
        id: "16",
        name: "J&T Express",
        slug: "jnt-express",
        industry: "Logistik",
        city: "Jakarta",
        description:
            "Perusahaan logistik dan ekspedisi terkemuka di Indonesia, menyediakan layanan pengiriman cepat dan terpercaya.",
        career_url: "https://jet.co.id/career",
        hash_signature: null,
        email: "hr@jet.co.id",
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/j&t-express-indonesia",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/jabordjekssindonesia",
        status: "ACTIVE",
        last_verified_at: "2026-02-25T13:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-25T13:00:00Z",
    },
    {
        id: "17",
        name: "Kompas Gramedia",
        slug: "kompas-gramedia",
        industry: "Media & Hiburan",
        city: "Jakarta",
        description:
            "Grup media terbesar di Indonesia, bergerak di bidang penerbitan, media cetak & digital, perhotelan, dan pendidikan.",
        career_url: "https://career.kompasgramedia.com/",
        hash_signature: null,
        email: "recruitment@kompasgramedia.com",
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/kompas-gramedia",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/kompasgramedia",
        status: "ACTIVE",
        last_verified_at: "2026-02-24T16:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-24T16:00:00Z",
    },
    {
        id: "18",
        name: "Ruangguru",
        slug: "ruangguru",
        industry: "Pendidikan",
        city: "Jakarta",
        description:
            "Platform edtech terbesar di Indonesia, menyediakan layanan bimbingan belajar online, kursus, dan solusi pendidikan digital.",
        career_url: "https://career.ruangguru.com/",
        hash_signature: null,
        email: "career@ruangguru.com",
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/ruangguru",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/ruangguru",
        status: "FLAGGED",
        last_verified_at: "2026-02-20T10:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-20T10:00:00Z",
    },
    {
        id: "19",
        name: "Sinar Mas Land",
        slug: "sinar-mas-land",
        industry: "Properti & Konstruksi",
        city: "Tangerang",
        description:
            "Pengembang properti terbesar di Indonesia, mengembangkan kawasan hunian, komersial, dan kawasan industri terpadu.",
        career_url: "https://career.sinarmasland.com/",
        hash_signature: null,
        email: "recruitment@sinarmasland.com",
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/sinarmasland",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/sinarmas_land",
        status: "ACTIVE",
        last_verified_at: "2026-02-27T09:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-27T09:00:00Z",
    },
    {
        id: "20",
        name: "Toyota Astra Motor",
        slug: "toyota-astra-motor",
        industry: "Otomotif",
        city: "Jakarta",
        description:
            "Distributor utama kendaraan Toyota di Indonesia, anak perusahaan Astra International dan Toyota Motor Corporation.",
        career_url: "https://www.toyota.astra.co.id/corporate-info/career",
        hash_signature: null,
        email: null,
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/toyota-astra-motor",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/toyotaid",
        status: "ACTIVE",
        last_verified_at: "2026-02-26T15:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-26T15:00:00Z",
    },
    {
        id: "21",
        name: "Bank Rakyat Indonesia (BRI)",
        slug: "bank-bri",
        industry: "Banking & Finance",
        city: "Jakarta",
        description:
            "Bank BUMN terbesar di Indonesia berdasarkan jumlah nasabah. Fokus pada layanan perbankan mikro, kecil, dan menengah.",
        career_url: "https://e-recruitment.bri.co.id/",
        hash_signature: null,
        email: null,
        phone: "14017",
        linkedin_url: "https://www.linkedin.com/company/bank-bri",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/bankbri_id",
        status: "ACTIVE",
        last_verified_at: "2026-02-28T11:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-28T11:00:00Z",
    },
    {
        id: "22",
        name: "Blibli",
        slug: "blibli",
        industry: "E-Commerce",
        city: "Jakarta",
        description:
            "Platform e-commerce omnichannel yang menyediakan produk orisinal dari berbagai kategori dengan jaminan 100% autentik.",
        career_url: "https://careers.blibli.com/",
        hash_signature: null,
        email: "career@blibli.com",
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/bliblidotcom",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/blabordjekli",
        status: "ACTIVE",
        last_verified_at: "2026-02-26T12:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-26T12:00:00Z",
    },
    {
        id: "23",
        name: "Tiket.com",
        slug: "tiketcom",
        industry: "Technology",
        city: "Jakarta",
        description:
            "Online Travel Agent (OTA) terkemuka di Indonesia, menyediakan pemesanan tiket pesawat, hotel, kereta, dan atraksi.",
        career_url: "https://www.tiket.com/careers",
        hash_signature: null,
        email: "careers@tiket.com",
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/tiabordjek",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/tiketcom",
        status: "FLAGGED",
        last_verified_at: "2026-02-18T10:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-18T10:00:00Z",
    },
    {
        id: "24",
        name: "Indosat Ooredoo Hutchison",
        slug: "indosat-ooredoo-hutchison",
        industry: "Telekomunikasi",
        city: "Jakarta",
        description:
            "Perusahaan telekomunikasi digital terkemuka di Indonesia hasil merger Indosat Ooredoo dan Tri Indonesia.",
        career_url: "https://ioh.co.id/portal/id/career",
        hash_signature: null,
        email: null,
        phone: "185",
        linkedin_url:
            "https://www.linkedin.com/company/indosat-ooredoo-hutchabordjek/",
        whatsapp: null,
        maps_url: null,
        instagram_url: "https://www.instagram.com/indosatooredoohutchison",
        status: "ACTIVE",
        last_verified_at: "2026-02-27T13:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-27T13:00:00Z",
    },
    {
        id: "25",
        name: "Kalbe Farma",
        slug: "kalbe-farma",
        industry: "Kesehatan",
        city: "Jakarta",
        description:
            "Perusahaan farmasi terbesar di Asia Tenggara, memproduksi obat resep, produk kesehatan, nutrisi, dan distribusi.",
        career_url: "https://career.kalbe.co.id/",
        hash_signature: null,
        email: "recruitment@kalbe.co.id",
        phone: null,
        linkedin_url: "https://www.linkedin.com/company/kalbe-farma",
        whatsapp: null,
        maps_url: null,
        instagram_url: null,
        status: "ACTIVE",
        last_verified_at: "2026-02-25T15:00:00Z",
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-02-25T15:00:00Z",
    },
];

// Helper functions for mock data operations
export function getCompanies(): Company[] {
    return companies;
}

export function getCompanyBySlug(slug: string): Company | undefined {
    return companies.find((c) => c.slug === slug);
}

export function searchCompanies(
    query: string,
    industry?: string,
    city?: string
): Company[] {
    let results = companies;

    if (query) {
        const q = query.toLowerCase();
        results = results.filter(
            (c) =>
                c.name.toLowerCase().includes(q) ||
                c.description.toLowerCase().includes(q)
        );
    }

    if (industry && industry !== "all") {
        results = results.filter((c) => c.industry === industry);
    }

    if (city && city !== "all") {
        results = results.filter((c) => c.city === city);
    }

    return results;
}

export function getStats() {
    const total = companies.length;
    const active = companies.filter((c) => c.status === "ACTIVE").length;
    const flagged = companies.filter((c) => c.status === "FLAGGED").length;
    const industries = [...new Set(companies.map((c) => c.industry))].length;
    const cities = [...new Set(companies.map((c) => c.city))].length;
    return { total, active, flagged, industries, cities };
}
